{
 "title": "devops",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Error Logs ",
   "type": "logs",
   "description": "Only ERROR level logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{app=\"devops-python\"} | json | level!=\"INFO\"\n"
    }
   ]
  },
  {
   "title": "Log Level Distribution",
   "type": "timeseries",
   "description": "Count by log level (last 5 min)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by (level) (count_over_time({app=\"devops-python\"} | json [5m]))\n"
    }
   ]
  },
  {
   "title": "Request Rate",
   "type": "timeseries",
   "description": "Logs per second",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum by (app) (rate({app=\"devops-python\"}[1m]))\n"
    }
   ]
  },
  {
   "title": "Applicaton logs",
   "type": "logs",
   "description": "Recent logs from all applications",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "{app=\"devops-python\"}"
    }
   ]
  }
 ]
}